### PR TITLE
General Refactoring 

### PR DESCRIPTION
**Pull request by Carelvd**
Dear Mr. Knupp,

I was hoping to make this PR against a `development` branch in your repository but it seems that Github does not allow for this and forces one to push to an existing branch, so I went with the master branch again, I trust this is fine with you.

I have tried to follow the Flask Extension/Pallets Project [guidelines](https://flask.palletsprojects.com/en/1.1.x/extensiondev/#approved-extensions) with this PR. The major changes are as follows :
 * Major refactorings are as follows :
    * Moving the functions within `app.py` into their "parent" modules e.g. `register_service` is now the `register` function in `service.py`, similarly there are register functions in `model.py`, `views.py`, `exception.py` and `admin.py`.
    * Splitting of the logic in `flask_sandman.app:application` into  `flask_sandman.api:sandman` so that there is a central function any user of the library can invoke within their own `create_app` methods. I have also refactored this into a `Sandman` class akin to `SQLAlchemy` or `Api` from flask restful but it's rough and omitted from this PR.
   * Combining `_register_user_models`  and `_reflect_all` into `flask_sandman.api:sandman` removing the need for the `reflect_all` flag. This was a touch more intricate then I initially realized.
   * Within `flask_sandman.app:application` there is a "router" variable this is assigned either the application or, if one is provided, a blueprint. I am developing an application against this feature and haven't had any trouble when using a blueprint so far. I haven't had the chance to port my experiences to uni test in Sandman just yet though.
 * Renaming of the package components to conform to the "standard" structure it seems Palette encourages :
    * Renaming the base package from `Sandman2` to `flask_sandman`.
    * Renaming `get_app` to `create_app`; internally this is called `application` but it is exposed to the user as `create_app` e.g. `from flask_sandman import create_app`.

I have also done some work on the documentation. This is still a bit rough though and I thought it best to make another PR's if this one is accepted.

### CODE REVIEW

**Comment by Carelvd** [comment]
Drat, I used f"{format}" strings and didn't realise you were testing in Python 2.7 and 3..5.

**Comment by Carelvd** [comment]
Hi Jeff, 

I figure you're busy but I was wondering if there was a reason this was not being accepted. If I must explain any of my modifications please let me know.

Regards,

   Carel

**Comment by Carelvd** [comment]
@jeffknupp I believe I have updated my branch to make merging with your more seamless. I'm a bit new to how PR's on Github pull through from my fork to your repository so may be pull through into a merging branch first.

**Comment by barraponto** [comment]
I was looking into rebasing this but it seems like parts of it have already made it in the final code, is that so?

**Comment by Carelvd** [comment]
I made this PR a while ago, if parts of this have made it into the code base though then that is news to me. I structured this so that one could step through the commits and merge them in one by one. Perhaps that has happened ?

I am still interested in getting this into the code base though as it stratifies the package so one can use the top most layer `sandman(app,...)` or peel off one or more layers and claim ever more control over the internal structure e.g. ripping off the first layer should allow one to have the following control for instance ...
```
database = ....
models = ...
views =...
_sandman_(app, database=database, models=models, views=views)
```

I was going to see what the status was with this once my current project is done (It'll be a few more weeks now) and I'd have the time to do so again, if nothing is merged in by then I was thinking of forking and releasing my own variant but I'm quite against that out of principle. 

Is it possible to be registered as a developer for this project or is it preferable to do things through PRs ?

**Comment by jeffknupp** [comment]
@Carelvd I'm -1 on renaming as a Flask extension, as (from the simplest user's perspective) the fact that `sandman2` is implemented using Flask shouldn't matter. Of course, because it *is* using Flask and because of Flask's popularity, I made it play nicely but purposefully did *not* make it a proper flask extension. There are some nice things here but I'd like to do a coherent pull, so if you (or anyone) is still interested in getting some of this in there please create an issue and we can discuss scope there.

**Pull request closed without merging**
