### PR TITLE
[WIP] Swagger

### PR DESCRIPTION
**Pull request by jmcarp**
Auto-document API using Swagger.

Todo:
- [ ] Serialize responses using Marshmallow
- [ ] Add Swagger markup for query parameters
- [ ] Add Swagger markup for pagination
- [ ] Write unit tests

### CODE REVIEW

**Comment by jeffknupp** [comment]
I'm super-interested in swagger integration but, again, would appreciate if you create a new branch to isolate changes to swagger-specific stuff.

**Comment by astewart-twist** [comment]
This would be amazing!

**Comment by srault95** [comment]
+1

**Comment by masaeedu** [comment]
@jeffknupp Was this merged somewhere else or did you decide not to take the PR?

**Comment by arivero** [comment]
Perhaps a second round could be done here with code from fastapi? https://github.com/tiangolo/fastapi

**Pull request closed without merging**
